import type { Metadata } from "next"

import "@/styles/globals.css"

import RootProvider from "@/components/RootProvider"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <RootProvider>{children}</RootProvider>
      </body>
    </html>
  )
}
