import type { Metadata } from "next"
import { Inter } from "next/font/google"

import "@/styles/globals.css"

import RootProvider from "@/components/RootProvider"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

const inter = Inter({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
  variable: "--font-poppins",
  style: "normal",
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`antialiased ${inter.className}`}>
        <RootProvider>{children}</RootProvider>
      </body>
    </html>
  )
}
